/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.3/samples
 * This project uses @Incubating APIs which are subject to change.
 */


plugins {
  java 
  application
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}


dependencies {
    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use TestNG test framework
            useTestNG("7.4.0")
        }
    }
}


sourceSets {
    main {
        java {
            setSrcDirs(listOf("app/src/main/java"))
        }
    }
    test {
        java {
            setSrcDirs(listOf("app/src/test/java"))
        }
    }
}

application {
  mainClass.set("com.craftinginterpreters.lox.Lox")
}
